---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	fetch(fetch)
	classify(classify)
	clarify(clarify)
	extract(extract)
	map(map)
	critic(critic)
	report(report)
	out_of_scope(out_of_scope)
	review_queue(review_queue)
	__end__([<p>__end__</p>]):::last
	__start__ --> fetch;
	clarify -.-> extract;
	clarify -.-> out_of_scope;
	clarify -.-> review_queue;
	classify -.-> clarify;
	classify -.-> extract;
	classify -.-> out_of_scope;
	critic --> report;
	extract --> map;
	fetch --> classify;
	map --> critic;
	out_of_scope --> __end__;
	report --> __end__;
	review_queue --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
